### ISSUE TITLE
Interaction with Grue mod

### ISSUE THREAD

**Issue by Chaogomu** [Maxwell-lt/MobBlocker#19]
The Grue from https://mods.curse.com/mc-mods/minecraft/235133-grue spawns and skills the player in protected chunks.

Not sure if I want this one to be fixed.

**Comment by Maxwell-lt** [comment]
Yeah, I know that mod's deal. I likely *could* fix it, but I agree that the fix may break that mod.

**Comment by Shinoow** [comment]
Considering Grues can hunt you down and kill you even in peaceful (due to existing for a single tick is long enough for the collision code to run, landing at least one hit), preventing it would to some degree break it (since you'd be able to walk into a protected chunk instead of letting the timer tick down, stopping the Grue from spawning).
A simple config option that checks in the spawn event if the Grue is spawning inside a protected area (as I believe the spawn even should fire off for that) could easily take care of it, but should that be something the player can bypass because they're inside a protected area? I would leave it as it is right now, since a Grue spawning is an indicator you've been in the darkness for too long, so I'd personally say it's on the player to ensure it's lit up enough where they live.

**Comment by Maxwell-lt** [comment]
Thanks for the feedback. Guess I'll close this for now.
