### ISSUE TITLE
1.11.2-1.4.0 crashes server while playing

### ISSUE THREAD

**Issue by kreezxil** [Maxwell-lt/MobBlocker#32]
No idea what anyone had done as this was submitted to me far after the fact.

http://paste.fedoraproject.org/539098/14856481/

**Comment by Maxwell-lt** [comment]
I didn't change anything related to the crashing method, so this isn't a new bug. This was probably caused by a mob deriving from IRangedMob that does something strange to arrows. The exact function that is being called from my mod that Minecraft doesn't like is EntityArrow.setVelocity(). Apparently it doesn't exist for this arrow.

If someone just randomly sent you a crashlog, there's nothing I can do.

Here's some information I'd like to have:
* The player "livn4the1" appears to be the one in range of the erroring Chunk Protector. Is it possible to ask what this player was doing? What mobs that can shoot arrows this player was aware of being around?
* What mobs are added to the game that shoot projectiles with this modlist?
* The best thing possible would be instructions on how to reproduce, and a minimal list of the mods required to cause the crash. It sounds like you aren't capable of getting that, though.

**Comment by Maxwell-lt** [comment]
What I can do, is release a patch that adds a config for the arrow velocity thing. Without using that method to stop the arrow in its tracks, the arrow has an extra tick to fly towards the player, making the absolutely-safe zone a bit smaller.

**Comment by Maxwell-lt** [comment]
Actually, it looks like the method I was using was a client-only method, and didn't actually affect the arrow itself. (and of course the client-sided method crashed the server when run.) I'll release a fix in a few minutes.
