### ISSUE TITLE
Item no match in the recipe xD (mobblocker-1.11.2-1.4.1)

### ISSUE THREAD

**Issue by Lightone** [Maxwell-lt/MobBlocker#34]
like this.

![2017-04-01_22 21 30](https://cloud.githubusercontent.com/assets/2113099/24584176/8d11e5ba-172a-11e7-9ae0-7bcfb38b63ed.png)

But the recipe work fine with glass of water.

**Comment by Maxwell-lt** [comment]
I don't see what the problem is. The recipe works with any item with the ID `minecraft:potion`, which includes the Uncraftable Potion. The recipe has no checks for NBT or metadata.

It appears that you are reporting that JEI is showing an Uncraftable Potion when any potion works as being a bug, in which case this issue is on JEI's end and should be reported to JEI.

Closed until the issue is shown to be on my end.
