### ISSUE TITLE
Prevent naturally spawning hostile mobs

### ISSUE THREAD

**Issue by GrzechuGrek** [Maxwell-lt/MobBlocker#44]
Hi. I like you to add option that prevent naturally spawning hostile mobs in case, if teleporting them away option is off. Just like MagnumTorch mod - prevent hostile mobs to spawn in darkness but no from mob spawner block nor from spawn egg.
And this option should be cofigurable(on/off) and applies to chunk protection block and area protection block.

Due to problem is, when I build building, with no light inside and with chunk/area protection block in, then hostile mobs does spawn inside and immedially are teleported away. Then they constantly appear outside in large amount even during day. This can be bothersome and troublesome.

**Comment by Maxwell-lt** [comment]
The solution to that issue is to light up the area. As long as you're within the protected area, it should be perfectly safe to dig down and light all the caves. The Chunk Protector has the most area to light, but it decays, and the Area Protector covers a small area by default.

For now, I won't add this feature; other mods have spawn-blocking capabilities if you want to prevent spawns in the area.
